sudo: false

language: node_js
node_js:
  - 10

branches:
  only:
    - master

install:
  - npm install

cache:
  directories:
    - node_modules

dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

deploy:
  provider: heroku
  app: "games-book"
  api_key:
    secure: "a6691e4d-8526-4211-bee0-04beffcdc2ed"