sudo: false

language: node_js
node_js:
  - 9

branches:
  only:
    - master

script:
  - npm run build
  - npm run client && npm run test

deploy:
  provider: heroku
  app: "games-book"
  api_key:
    secure: "a6691e4d-8526-4211-bee0-04beffcdc2ed"